# Generated by Django 3.1.6 on 2021-03-04 19:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created', models.FloatField(default=1614887493.8553889)),
                ('modified', models.FloatField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('products', models.JSONField()),
                ('billing_address', models.JSONField()),
                ('payment', models.JSONField()),
                ('shipping_price', models.PositiveIntegerField(default=0)),
                ('total_products_price', models.PositiveIntegerField(default=0)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
                ('shop', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
