# Generated by Django 3.1.6 on 2021-03-04 19:51

from django.db import migrations, models
import django.db.models.deletion
import globals.image
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created', models.FloatField(default=1614887493.8553889)),
                ('modified', models.FloatField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField(default=1)),
                ('description_short', models.CharField(blank=True, max_length=200, null=True)),
                ('description_long', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('shop', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=75)),
                ('value', models.TextField()),
                ('index', models.IntegerField(default=-1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to=globals.image.RenameImage('images'))),
                ('index', models.PositiveIntegerField(default=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
    ]
